name: CI
run-name: ${{ github.actor }} is executing the CI
on: [push]
jobs:
  latexmk:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build image
        run: docker build -t latex-template .devcontainer/
      - name: Compile
        run: docker run -i -v ${PWD}:/tmp -w /tmp latex-template latexmk -lualatex main.tex
