name: CI
run-name: ${{ github.actor }} is executing the CI
on: [push]
jobs:
  latexmk:
    runs-on: ubuntu-latest
    container: texlive/texlive
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Compile
        run: latexmk -lualatex main.tex
